# theme: jekyll-theme-midnight
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-paginate-v2

paginate: 5
paginate_path: "/page:num"

title: milo's homepage
description: Welcome to World of MIS!
