theme: jekyll-theme-midnight
# remote_theme: pages-themes/midnight@v0.2.0

plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num"

title: milo's homepage
description: Welcome to World of MIS!
